export type Role = 'admin' | 'manager' | 'member';

// Office-bearer titles from the constitution (Section C). A member can hold
// more than one — titles are interchangeable, not exclusive (deputies stand
// in for their principal — see DEPUTY_OF in roles.ts).
export type MemberTitle =
  | 'chairperson'
  | 'viceChairperson'
  | 'secretary'
  | 'viceSecretary'
  | 'treasurer'
  | 'coordinator'
  | 'disciplineMaster';

export type PaymentMethod = 'Cash' | 'Mpesa';
export type VerificationStatus = 'pending' | 'verified' | 'rejected';

export type ForumCategory =
  | 'Announcement'
  | 'Proposal'
  | 'Opportunity'
  | 'Observation'
  | 'Question'
  | 'Report'
  | 'General';

export type MinuteStatus = 'Draft' | 'Official';
export type MeetingType = 'virtual' | 'agm';

// Monthly dues auto-generated by the app; meetingFee/entryFee are one-off
// or per-meeting charges that share the same verification flow.
export type ContributionPurpose = 'monthly' | 'meetingFee' | 'entryFee';
export type ContributionStatus = 'Unpaid' | 'Pending' | 'Paid' | 'Late';

export type FineType = 'lateContribution' | 'virtualAbsence' | 'agmAbsence' | 'welfareArrears' | 'other';

export type ExitRequestStatus = 'pending' | 'approved' | 'rejected' | 'awaitingResale' | 'paidOut' | 'rejectedByVote';

export interface Vote {
  memberId: string;
  memberName: string;
  vote: 'approve' | 'reject';
  votedAt: number;
}

export interface SeenBy {
  memberId: string;
  memberName: string;
  seenAt: number;
}

export interface SignatoryApproval {
  memberId: string;
  memberName: string;
  approvedAt: number;
}

export interface Member {
  id: string;
  name: string;
  phone: string; // +254...
  role: Role;
  pinHash: string;
  mustChangePin: boolean;
  titles: MemberTitle[];
  secondary: boolean; // minor/secondary member per constitution Section B — higher monthly dues
  representing?: string; // adult's profile: memberId of the secondary member they represent
  representedBy?: string; // secondary member's own profile (if one exists): the adult's memberId
  failedAttempts: number;
  lockedUntil: number | null;
  isLocked: boolean; // computed at hydration: lockedUntil > Date.now()
  active: boolean;
  joinedAt: string; // YYYY-MM-DD
  createdAt: number;
  updatedAt: number;
}

/** Hydrate a Firestore member doc with computed fields */
export function hydrateMember(id: string, data: Record<string, unknown>): Member {
  const lockedUntil = (data.lockedUntil as number | null) ?? null;
  return {
    ...data,
    id,
    titles: (data.titles as MemberTitle[]) ?? [],
    secondary: (data.secondary as boolean) ?? false,
    lockedUntil,
    isLocked: lockedUntil !== null && lockedUntil > Date.now(),
  } as Member;
}

export interface Contribution {
  id: string;
  memberId: string;
  memberName: string;
  purpose: ContributionPurpose;
  month: string; // YYYY-MM — the month this charge belongs to
  amount: number;
  fineAmount: number;
  status: ContributionStatus;
  /**
   * Whether the fine on this record has actually been settled. Members often
   * pay the dues and leave the fine, so 'Paid' alone cannot mean both were
   * collected. Undefined on records written before this existed, which were
   * all-or-nothing — hydrateContribution defaults those to `status === 'Paid'`.
   */
  finePaid?: boolean;
  mpesaCode?: string;
  mpesaMessage?: string;
  treasurerMpesaCode?: string;
  verifiedBy?: string;
  verifiedAt?: number;
  paymentMethod?: PaymentMethod;
  paidDate?: string;
  recordedBy?: string;
  createdAt: number;
  updatedAt: number;
}

/** Hydrate a Firestore contribution doc with backward-compat defaults */
export function hydrateContribution(id: string, data: Record<string, unknown>): Contribution {
  return {
    ...data,
    id,
    purpose: (data.purpose as ContributionPurpose) ?? 'monthly',
    fineAmount: (data.fineAmount as number) ?? 0,
    finePaid: (data.finePaid as boolean | undefined) ?? data.status === 'Paid',
  } as Contribution;
}

export interface Fine {
  id: string;
  memberId: string;
  memberName: string;
  type: FineType;
  amount: number;
  reason: string;
  relatedId?: string; // e.g. the contribution or meeting this fine came from
  waived: boolean;
  waivedBy?: string;
  waivedAt?: number;
  createdBy: string;
  createdByName: string;
  createdAt: number;
}

export interface AttendanceRecord {
  id: string;
  meetingId: string;
  meetingDate: string;
  meetingType: MeetingType;
  memberId: string;
  memberName: string;
  present: boolean;
  excused: boolean;
  createdAt: number;
}

export interface Expense {
  id: string;
  date: string; // YYYY-MM-DD
  category: string; // dynamic, loaded from settings
  amount: number;
  notes: string;
  paymentMethod: PaymentMethod;
  status: VerificationStatus;
  votes: Vote[];
  seenBy: SeenBy[];
  recordedBy: string;
  recordedByName: string;
  createdAt: number;
}

/** Hydrate a Firestore expense doc with backward-compat defaults */
export function hydrateExpense(id: string, data: Record<string, unknown>): Expense {
  return {
    ...data,
    id,
    paymentMethod: (data.paymentMethod as PaymentMethod) ?? 'Cash',
    status: (data.status as VerificationStatus) ?? 'verified',
    votes: (data.votes as Vote[]) ?? [],
    seenBy: (data.seenBy as SeenBy[]) ?? [],
    recordedByName: (data.recordedByName as string) ?? '',
  } as Expense;
}

export interface BankTransaction {
  id: string;
  type: 'deposit' | 'withdrawal';
  amount: number;
  date: string;
  description: string;
  proposalId?: string; // linked forum proposal
  status: 'approved' | 'pending';
  approvals: SignatoryApproval[];
  seenBy: SeenBy[];
  recordedBy: string;
  recordedByName: string;
  createdAt: number;
}

/** Hydrate a Firestore bank transaction doc with backward-compat defaults */
export function hydrateBankTransaction(id: string, data: Record<string, unknown>): BankTransaction {
  return {
    ...data,
    id,
    status: (data.status as 'approved' | 'pending') ?? 'approved',
    approvals: (data.approvals as BankTransaction['approvals']) ?? [],
    seenBy: (data.seenBy as SeenBy[]) ?? [],
    recordedByName: (data.recordedByName as string) ?? '',
  } as BankTransaction;
}

export type InvestmentStatus = 'proposed' | 'active' | 'closed';

export interface Investment {
  id: string;
  title: string;
  description: string;
  amountInvested: number;
  expectedReturn?: number;
  actualReturn?: number;
  status: InvestmentStatus;
  proposalId?: string; // linked forum proposal
  recordedBy: string;
  recordedByName: string;
  createdAt: number;
  updatedAt: number;
}

export interface RefundBreakdown {
  contributionsPaid: number;
  welfarePaid: number;
  arrears: number;
  deductionPct: number;
  deductionAmount: number;
  netRefund: number;
}

export interface ExitRequest {
  id: string;
  memberId: string;
  memberName: string;
  initiatedBy: 'member' | 'admin';
  initiatedById: string;
  initiatedByName: string;
  reason: string;
  refundBreakdown: RefundBreakdown;
  votes: Vote[];
  status: ExitRequestStatus;
  paidOutAt?: number;
  createdAt: number;
  updatedAt: number;
}

export interface MeetingMinute {
  id: string;
  date: string;
  meetingType: MeetingType;
  chairedBy: string;
  secretary: string;
  attendees: string[];
  agendaItems: AgendaItem[];
  status: MinuteStatus;
  createdBy: string;
  createdAt: number;
  updatedAt: number;
}

export interface AgendaItem {
  title: string;
  discussion: string;
  resolutions: string;
}

export interface ForumReply {
  id: string;
  body: string;
  authorId: string;
  authorName: string;
  authorTitles: MemberTitle[];
  createdAt: number;
}

export interface ForumPost {
  id: string;
  title: string;
  body: string;
  category: ForumCategory;
  pinned: boolean;
  authorId: string;
  authorName: string;
  authorTitles: MemberTitle[];
  replies: ForumReply[];
  createdAt: number;
}

/** Hydrate a Firestore forum post doc with backward-compat defaults */
export function hydrateForumPost(id: string, data: Record<string, unknown>): ForumPost {
  return {
    ...data,
    id,
    pinned: (data.pinned as boolean) ?? false,
    authorTitles: (data.authorTitles as MemberTitle[]) ?? [],
    replies: ((data.replies as ForumReply[]) ?? []).map(r => ({
      ...r,
      authorTitles: r.authorTitles ?? [],
    })),
  } as ForumPost;
}

export interface Settings {
  groupName: string;
  groupShortName: string;

  // Membership & dues (Constitution Sections B, J)
  entryFee: number;
  monthlyContributionPrimary: number; // legacy flat rate — mirrors current group year (kept for back-compat)
  monthlyContributionSecondary: number;
  contributionRates: Record<string, { primary: number; secondary: number }>; // keyed by group year 'YYYY/YYYY' (Jul–Jun)
  meetingFee: number;
  memberCap: number;

  // Automation — first month ('YYYY-MM') the app auto-generates monthly dues.
  // Set to the AGM month of the 2026/27 year ('2026-10'); earlier months are
  // entered manually by the treasurer via the Ledger Entry screen.
  autoDuesFrom: string;

  // Fines & penalties (Constitution "Fines and Penalties")
  contributionCutoffDay: number; // day of the FOLLOWING month a monthly contribution is due by
  lateContributionFine: number;
  virtualAbsenceFine: number;
  agmAbsenceFine: number;

  // Welfare payouts (Constitution Section K)
  welfareParentDeath: number;
  welfareNuclearDeath: number;
  welfareMemberDeath: number;

  // Exit terms (Constitution Section E)
  exitDeductionPct: number; // 0.2 = 20%

  // Meetings
  agmDate: string; // MM-DD, e.g. '10-20'

  // Opening balances
  openingCashBalance: number;
  openingBankBalance: number;
  openingAgmFundBalance: number;
  openingBalancesSet: boolean;

  expenseCategories: string[];
}
